### PR TITLE
feat: add fastrtps as module

### PR DESCRIPTION
**Pull request by wep21**
- use fastrtps, fastcdr as bzlmod module

### CODE REVIEW

**Comment by wep21** [comment]
@daohu527 What do you think about the change?

**Comment by daohu527** [comment]
@wep21 Yes, I am ready want to do that, but there are a few problems here.
1.  I need to upgrade the version of fastdds.  ref [link](https://cx8sal2qit.feishu.cn/wiki/MfMgwbgtJiHXSQk3FjjcxzTLnec?fromScene=spaceOverview). After the upgrade, this patch is basically invalid. Someone has reported the deadlock problem to me.
2. I also need to use blzmod for fastdds's dependencies. I see that the latest fastdds also depends on openssh, so I think these also need to be clarified.

Or if you have any ideas, let's take a look together.

**Comment by wep21** [comment]
I try to build fastdds 2.14.2 by bzlmod without any patch first.
Then, try to apply patch to work with cyberrt. I'm not familiar with the changes, so I appreciate it if you could cowork with me.

**Comment by daohu527** [comment]
sure, here is an bazel work about https://github.com/daohu527/Fast-DDS

**Comment by daohu527** [comment]
@wep21 I found foonathan_memory include path is not match with fastdds, The following is the include path parsed by bazel, but it does not match the actual path in `bazel-out`
```
-isystem bazel-out/k8-fastbuild/bin/include/foonathan_memory -isystem bazel-out/k8-fastbuild/bin/external/foonathan_memory~/libfoonathan_memory-0.7.3/include 
```

we should add 
```
+cmake(
+    name = "foonathan_memory",
+    build_args = [
+        "--",
+        "-j4",
+    ],
+    cache_entries = cache_entries,
+    lib_source = ":all_srcs",
+    lib_name = "libfoonathan_memory-0.7.3",
+    out_include_dir = "include/foonathan_memory",   // here
+    visibility = ["//visibility:public"],
+)
```

**Comment by daohu527** [comment]
close and move to https://github.com/wheelos/core/pull/32

**Pull request closed without merging**
